// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/alex/workspace/ReactNativeApp/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/alex/workspace/ReactNativeApp/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('ReactNativeApp', appParameters);
});
require('/Users/alex/workspace/ReactNativeApp/index.js');